[workspace]
resolver = "2"
members = [
    "crates/lunaria",
    "crates/lunaria-editor",
    "crates/lunaria-assets", "crates/lunaria-core", "crates/lunaria-database",
]

default-members = [
    "crates/lunaria"
]

[workspace.dependencies]
lunaria-editor = { path = "crates/lunaria-editor" }
lunaria-assets = { path = "crates/lunaria-assets" }

gpui-kit = "0.6"
thiserror = "2"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
